version: 2.1

commands:
  setup_codebase:
    description: "Loads the workspace with our persisted code and build artifacts"
    steps:
      - attach_workspace:
          at: /home/app
  store_output:
    description: "Standardizes where test artifacts are stored"
    steps:
      - store_artifacts:
          path: /tmp/circle/test_reports
      - store_test_results:
          path: /tmp/circle/test_reports

defaults: &defaults
  working_directory: &working_directory /home/app/current
  parallelism: 1
  shell: /bin/bash --login
  environment:
    CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    RACK_ENV: "test"
    RAILS_ENV: "test"
  docker:
  - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
    command: /sbin/init

workflows:
  version: 2
  test:
    jobs:
      - build
      - rspec:
          requires:
            - build

jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-
        - v1-dep-
    - run: gem install bundler -v "=1.13.6"
    - run: mkdir -p tmp/cache
    - run:
        name: bundle
        command: |
          bundle check --path=~/mavenlink/mavenlink_gem/bundle || bundle install --path=~/mavenlink/mavenlink_gem/bundle --jobs=8 --retry=3
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/mavenlink/mavenlink_gem/bundle
    - persist_to_workspace:
        root: /home/app
        paths:
          - current/.bundle
          - bundle
  rspec:
    <<: *defaults
    steps:
    - setup_codebase
    - run:
        name: Run RSpec tests
        command: |
          bundle exec rspec --color --format progress --format RspecJunitFormatter --out $CIRCLE_TEST_REPORTS/rspec/test-results.xml
    - store_output

